### ISSUE TITLE
Consume topics on MacOS build 1.5.1

### ISSUE THREAD

**Issue by mik-sher** [RPG-18/plumber#44]
Hey! 

On released version 1.5.1 (arm62 and x86_64) i can't consume any topic: After click "lens" button on topic list, nothing happens.
On version 1.5.0 all works fine. 

Configuration: 
MacBook Pro (13-inch, M1, 2020)
MacOS 12.2.1 (21D62)

**Comment by RPG-18** [comment]
Hi. Thanks.  I'll take a look on this weekend

**Comment by mik-sher** [comment]
If you need any additional information, I'll be glad to help.

**Comment by RPG-18** [comment]
@mik-sher try to run https://github.com/RPG-18/plumber/releases/tag/v1.5.2

**Comment by RPG-18** [comment]
Can i close issue?

**Comment by mik-sher** [comment]
@RPG-18 Sorry for the long reply. Everything works fine now (version 1.5.2 arm62 and x86_64), thanks a lot 👍
